import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import solc from "solc";

const sources = {
  "ShieldedVerifierMock.sol": { content: readFileSync("contracts/ShieldedVerifierMock.sol", "utf8") },
  "ShieldedPool.sol": { content: readFileSync("contracts/ShieldedPool.sol", "utf8") },
  "VeilTreasury.sol": { content: readFileSync("contracts/VeilTreasury.sol", "utf8") },
  "VeilAttestationRegistry.sol": { content: readFileSync("contracts/VeilAttestationRegistry.sol", "utf8") },
  "VeilHook.sol": { content: readFileSync("contracts/VeilHook.sol", "utf8") },
  "VeilShieldRouter.sol": { content: readFileSync("contracts/VeilShieldRouter.sol", "utf8") },
  "VeilCreate2Deployer.sol": { content: readFileSync("contracts/VeilCreate2Deployer.sol", "utf8") },
};

const input = {
  language: "Solidity",
  sources,
  settings: {
    optimizer: { enabled: true, runs: 200 },
    viaIR: true,
    evmVersion: "cancun",
    outputSelection: { "*": { "*": ["abi", "evm.bytecode.object", "evm.deployedBytecode.object"] } },
  },
};

console.log("Compiling Veil smart contracts...");
const out = JSON.parse(
  solc.compile(JSON.stringify(input), {
    import(path) {
      if (path.startsWith("@openzeppelin/") || path.startsWith("@uniswap/")) {
        try {
          return { contents: readFileSync(`node_modules/${path}`, "utf8") };
        } catch {
          return { error: `Unable to resolve ${path}` };
        }
      }
      const local = path.replace(/^\.\//, "");
      if (sources[local]) return { contents: sources[local].content };
      return { error: `Unable to resolve ${path}` };
    },
  })
);

const errors = (out.errors ?? []).filter((e) => e.severity === "error");
if (errors.length > 0) {
  for (const e of errors) console.error(e.formattedMessage);
  process.exit(1);
}

for (const [file, name] of [
  ["VeilHook.sol", "VeilHook"],
  ["VeilShieldRouter.sol", "VeilShieldRouter"],
  ["ShieldedPool.sol", "ShieldedPool"],
]) {
  const bytes = out.contracts[file][name].evm.deployedBytecode.object.length / 2;
  if (bytes > 24_576) {
    throw new Error(`${name} runtime bytecode exceeds EIP-170 limit (${bytes} bytes).`);
  }
  console.log(`✓ ${name} runtime bytecode: ${bytes} bytes`);
}

const exportArtifactTs = (name, contract) =>
  `export const ${name}_ABI = ${JSON.stringify(contract.abi)} as const;\nexport const ${name}_BYTECODE = "0x${contract.evm.bytecode.object}";`;

const exportArtifactJs = (name, contract) =>
  `export const ${name}_ABI = ${JSON.stringify(contract.abi)};\nexport const ${name}_BYTECODE = "0x${contract.evm.bytecode.object}";`;

const artifactsList = [
  ["SHIELDED_VERIFIER_MOCK", out.contracts["ShieldedVerifierMock.sol"]["ShieldedVerifierMock"]],
  ["SHIELDED_POOL", out.contracts["ShieldedPool.sol"]["ShieldedPool"]],
  ["VEIL_TREASURY", out.contracts["VeilTreasury.sol"]["VeilTreasury"]],
  ["VEIL_ATTESTATION_REGISTRY", out.contracts["VeilAttestationRegistry.sol"]["VeilAttestationRegistry"]],
  ["VEIL_HOOK", out.contracts["VeilHook.sol"]["VeilHook"]],
  ["VEIL_SHIELD_ROUTER", out.contracts["VeilShieldRouter.sol"]["VeilShieldRouter"]],
  ["VEIL_CREATE2_DEPLOYER", out.contracts["VeilCreate2Deployer.sol"]["VeilCreate2Deployer"]],
];

const tsContent = `// GENERATED by scripts/compile.mjs — do not edit.
export const VEIL_SOLC_VERSION = "${solc.version().split("+")[0]}";

${artifactsList.map(([name, c]) => exportArtifactTs(name, c)).join("\n\n")}
`;

const jsContent = `// GENERATED by scripts/compile.mjs — do not edit.
export const VEIL_SOLC_VERSION = "${solc.version().split("+")[0]}";

${artifactsList.map(([name, c]) => exportArtifactJs(name, c)).join("\n\n")}
`;

mkdirSync("lib", { recursive: true });
writeFileSync("lib/veil-artifact.ts", tsContent);
writeFileSync("lib/veil-artifact.mjs", jsContent);
console.log("✓ Successfully wrote compiled artifacts to lib/veil-artifact.ts and .mjs");
